### ISSUE TITLE
Python dependencies which come from pip need to be isolated in a virtualenv

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/charmbox#18]
As discovered in `charmbox:devel`

Any dependencies incoming from pip needs to be installed in a virtualenv, and made available via the virtualenv. Otherwise, its going to have to be packaged.

**Comment by tvansteenburgh** [comment]
bundletester has always depended on charm-tools. The breakage you're seeing is due to charm-tools now depending on theblues, which had incorrectly pinned its requests dep to 2.6.0, breaking everything that depended on requests (unpinned) and theblues.

**Comment by tvansteenburgh** [comment]
This problem will go away when this is released: https://github.com/juju/theblues/pull/20

**Comment by marcoceppi** [comment]
It was released

**Comment by lazypower** [comment]
Oh nice, so the description is a bit misleading, but the end consensus is to still isolate bundletester in a virtualenv I think. - so i took the liberty of trimming it down to just the necessary parts

**Comment by lazypower** [comment]
I think this is mostly deprecated/stale. If this is not the case please re-open
