### ISSUE TITLE
Need build instructions for charmbox

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/charmbox#31]
We should create a build.md file that outlines how to update or build charmbox for ourselves.

**Comment by lazypower** [comment]
see README.md subheading

Building Charmbox from Source

git clone https://github.com/juju-solutions/charmbox.git && cd charmbox
sudo docker build -t charmbox .
sudo docker run --rm -ti charm box

We could probably expand on whats there, but we have some build instructions.

**Comment by lazypower** [comment]
Is this still an issue that needs further work or are we good to close this with the bits already in the readme?

**Comment by mbruzek** [comment]
Looks like the README.md has build instructions.
