### ISSUE TITLE
Create a daily build process for devel branch

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/charmbox#32]
We noticed that the charmbox:devel branch will only be built on something pushing to the repository. The juju-core team could release many versions between pushes to this repository.

@johnsca asked if we could set up a daily build of the devel branch. 

I went to the Docker hub, and clicked on "Build Settings" scrolled down to "Build trigger" and expanded examples.

We could trigger a build from curl if we schedule something on cron to run daily.

curl -H "Content-Type: application/json" --data '{"docker_tag": "devel"}' -X POST https://registry.hub.docker.com/u/jujusolutions/charmbox/trigger/TOKEN_REDACTED/

The ask is to figure out if daily builds are ok and where to run the cron so other people can access it while people are out.

**Comment by lazypower** [comment]
if you look at the registry, its already being built daily.

https://hub.docker.com/r/jujusolutions/jujubox/builds/
and
https://hub.docker.com/r/jujusolutions/charmbox/builds/

They get built daily at 3am EDT

**Comment by mbruzek** [comment]
@johnsca and I were not able to determine the regularity of the build looking at those settings.

The original problem was charmbox still had the beta3 release when there was a beta5. We created this issue, then found the problem was with the packaging, which we fixeds in a different area.
