### ISSUE TITLE
need to install azure cli npm package in charmbox

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/charmbox#8]
I am trying to use Azure with the 2.0 version of Juju and the docs recommend that I have the azure-cli installed, which requires npm. https://jujucharms.com/docs/devel/config-azure

Please add npm and azure-cli to the build process.

**Comment by lazypower** [comment]
This is kind of a one-time-use dependency, and exactly what charmbox was designed to be good at. Install that one time dep, edit your environment config and let the container wash away those dependencies you dont need to keep around.

Good thought though, thanks for filing the bug.

**Comment by mbruzek** [comment]
Would it be possible to automate the install of npm, azure-cli and generation of certs with a container that starts with npm?  Like a helper container to charmbox?

**Comment by lazypower** [comment]
Actually, yeah, if we map in the docker socket when running charmbox, and then add small dockerfiles for utility functions, its completely possible to build out helper images that keep dependencies out of the principal container 'charmbox'. 

I've thought about using a data volume for the JUJU_HOME as well, which would make this even easier. 

What do you think?
